[build]
	base = "."
	publish = "public/"
	command = "npm run build"

[[redirects]]
	from = "/cms/*"
	to = "https://testcms.lpld.io/cms/:splat"
	status = 200
	force = true

[[redirects]]
	from = "/media/*"
	to = "https://testcms.lpld.io/media/:splat"
	status = 200
	force = true